local opt = vim.opt

opt.nu = true
opt.rnu = true
vim.g.netrw_browse_split = 0
vim.g.netrw_banner = 0

opt.expandtab = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.breakindent = true
opt.hlsearch = false
opt.incsearch = true
opt.ignorecase = true
opt.smartcase = true
opt.undofile = true
opt.wrap = false
opt.scrolloff = 8
opt.clipboard = "unnamedplus"
opt.updatetime = 50
opt.pumheight = 10
opt.laststatus = 3
opt.termguicolors = true
opt.splitright = true
opt.splitbelow = true
opt.mouse = "a"
opt.signcolumn = "yes"
opt.cursorline = true
